name: webxr
description: Dart bindings for WebXR APIs.
version: 0.1.0
repository: https://github.com/your-username/webxr

environment:
  sdk: ^3.4.0

dependencies:
  es2023: ^0.2.0
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.10.0
  build_web_compilers: ^4.4.0
