dependencies:
  - static:
      package: ./type_fixes.dart
      types:
        - EventListenerOrEventListenerObject
  - dart:
      package: js_interop
      library: js_interop
  - pubDev:
      package: web
      library: web
  - pubDev:
      package: es2023
      library: es2023
  - package:
      name: es2023
sanitizer:
  phases:
    - mergeModules
    - mergeInterfaces
    - mergeInterfacesIntoClasses
    - missingTypeArgsAndParams
    - constructorInterfaces
    - invalidIdentifiers
